### ISSUE TITLE
Flag syntax needs to be changed in reference docs

### ISSUE THREAD

**Issue by deepthi** [vitessio/website#1042]
As documented in [VEP-4](https://github.com/vitessio/enhancements/blob/main/veps/vep-4.md), we have started the process of migrating to standard `pflag` usage.
Some of the docs don't yet reflect the recommended usage, so we need to fix those
https://vitess.io/docs/14.0/reference/programs/vtexplain/
https://vitess.io/docs/14.0/reference/programs/vtgate/

The rest (mysqlctl, vtctl, vtctld, vtadmin, vttablet) are correct. However, there is inconsistency in how the flags are listed. In some cases they are prefixed with `--`, in others, there is no prefix. We should make them all standard, my suggestion is to drop the `--` prefix.

**Comment by ajm188** [comment]
> We should make them all standard, my suggestion is to drop the `--` prefix.

Agreed, that's a good idea

**Comment by deepthi** [comment]
@vitessio/query-serving can one you pick up the vtgate/vtexplain docs?

**Comment by mattlord** [comment]
@ajm188 and @deepthi I'm sorry, but I disagree. I think that we should show the dashes because some vitess flags have a single dash (e.g. -v) and others have double dashes. It also clearly distinguishes flags from other variables like metrics, non-flag parameters, etc throughout the docs. Lastly, we also reference flags from other related programs and some use single dash for everything and others double. I think we should default to being explicit when it's not otherwise explicitly clear that things are a flag and from there to be consistent. I feel that the other proposal is choosing convenience for the writer over clarity for the reader and I'd prefer that be flipped.

It's also the norm to show the dashes for related docs, e.g.:
  - MySQL: https://dev.mysql.com/doc/refman/8.0/en/mysql-command-options.html
  - etcd: https://etcd.io/docs/v3.5/op-guide/configuration/
  - k8s: https://kubernetes.io/docs/reference/kubectl/kubectl/
  - golang: https://pkg.go.dev/flag

Also, all the other Reference->Program pages are using the double dashes already. 

Side benefits:
  - It's easier for the user to cut and paste from the docs (the full flag syntax)
  - It will hopefully be easier for us to leverage automation for this kind of output based on the help output from the program (which has the dashes in it)

And for the record, I think you went through the top level Reference->Programs pages and identified the two left (there are sub-pages like those under vtctl left too). I'm working on the other sections in the Reference section here: https://github.com/vitessio/website/pull/1046

I was planning to include the two noted pages FWIW.

**Comment by systay** [comment]
FWIW, I like Matt's arguments here 
¯\_(ツ)_/¯
