### ISSUE TITLE
[Feedback] Search Functionality

### ISSUE THREAD

**Issue by FancyFane** [vitessio/website#1355]
## Vitess.io Search
I know during one of the Vitess meetings the community has been asked for feedback on the search functionality. I'm having difficulty finding a vttablet option I know is in the documentation: `init_db_name_override`.  

![Screenshot from 2023-01-18 11-56-46](https://user-images.githubusercontent.com/10777037/213490195-883907ba-9e59-4255-a84d-0fc8d27a5f40.png)

## Google Search
When doing a google search for the phrase I get provided two pages, both of which could help provide the information I'm looking for. 

![Screenshot from 2023-01-19 09-56-36](https://user-images.githubusercontent.com/10777037/213490564-6cf075dc-87a4-4434-82c0-85ee07e4c955.png)

**Comment by orware** [comment]
Similarly, I believe I have been noticing the same with other searches too, I think ever since the Vitess site was updated sometime last year?

An example I can share is trying to find the page where the `workload` mode switch is detailed.

If I search for `olap` I get no results:
![image](https://user-images.githubusercontent.com/931650/213498206-7fc43a3a-bc46-42bb-8aa9-2ff82820e248.png)

If I search for `workload` I get two results, but not the one I'd like to get:
![image](https://user-images.githubusercontent.com/931650/213498312-cb7d06f1-9dc8-4c99-a41b-6301ae2a8bd9.png)

The actual documentation page I'd like to have mentioned in the results is the [MySQL Compatibility](https://vitess.io/docs/15.0/reference/compatibility/mysql-compatibility/#workload) page.

As @FancyFane shared above in their example, the relevant page is shown if a Google Search for something like `vitess olap` is made instead.

I've already bookmarked the MySQL Compatibility page to make things easier for me so it's less of an issue these days, but if the search results are limited/incorrect it may be making it more difficult for users to find what they need within the documentation compared to in the past.

**Comment by RobertKielty** [comment]
Myself and @thisisobate met just now to determine the  root cause of the problem. 

I have reproduced the problem as described above in my local environment, so thank you all for the clear steps to reproduce issue!   

Although both of us can see https://app.netlify.com/sites/vitess/deploys neither of us are members of the vitess team in Netlify so we _may_ need to request access when we come up with a fix. 

Next step here is to fully understand the problem. Update to follow.

**Comment by RobertKielty** [comment]
This is a WIP update, not there yet but we are getting closer.

We can now see why certain searches are failing;the keywords are not present in the dynamically built index.json

At its core the search uses https://lunrjs.com/docs/index.html which is wrapped up in hugo as follows...

Runtime usage of the index.json file 
Files of note  /layouts/_default/list.lunr.json

index.json is created by a `hugo build` 

Next step - understand the build process wrt index.json -  what gets included in the indexs and  what does not?

**Comment by thisisobate** [comment]
I have a fix in mind.
Would open a PR soon and share my thoughts
