### ISSUE TITLE
OnlineDDL documentation missing from reference/programs/vtctl page

### ISSUE THREAD

**Issue by FancyFane** [vitessio/website#1388]
## Problem Description

We have some documentation detailing how OnlineDDL works under the user-guides, however, we are missing this command from the vtctl page:

https://vitess.io/docs/16.0/user-guides/schema-changes/audit-and-control/

Documenting this as it's nice to have the refrence on hand without having to read through a user guide page

**Comment by Satarupa22-SD** [comment]
@FancyFane @mattlord please assign this issue to me if it's still open. Thanks.

**Comment by anshikavashistha** [comment]
@mattlord Do we have to add a section to the vtctl page documenting the OnlineDDL command, including its usage, options, and examples? or should document it in existing section of vtctl ?
I am working on this issue

**Comment by mattlord** [comment]
@FancyFane you're talking about this page? https://vitess.io/docs/reference/programs/vtctl/ 

If so, we could certainly do that. It's also worth noting, however, that `vtctl`/`vtctlclient` has been deprecated since v18 and we hope to remove it entirely in an upcoming release. The OnlineDDL commands are in the new client reference pages (which are built from the source): https://vitess.io/docs/reference/programs/vtctldclient/

**Comment by FancyFane** [comment]
@mattlord this is an older issue and is no longer relevant, we can close out this issue.
