### ISSUE TITLE
Vitess Netlify Deploy previews broken

### ISSUE THREAD

**Issue by morgo** [vitessio/website#429]
It looks like netlify has changed deploy previews on netlify.com to netlify.app.

This seems to have broken the previews. For example see [This Preview](https://deploy-preview-428--admiring-colden-94a5f1.netlify.app/) -- but it is the same with all PRs.

I am hoping this is something which is an easy fix, but it's outside of my expertise.

**Comment by morgo** [comment]
PTAL @celestehorgan @lucperkins

**Comment by celestehorgan** [comment]
@morgo Taking a look at the source code for the preview, I see the following for the stylesheet:

```
<link rel=stylesheet href=https://deploy-preview-428--admiring-colden-94a5f1.netlify.com/css/style.fce8dcf6d125f57a6808aac9c42c3905fee6883671c4b3fd6c26ed6596f41cb0.css integrity="sha256-/Ojc9tEl9XpoCKrJxCw5Bf7miDZxxLP9bCbtZZb0HLA=">
```

Note the **.com** suffix. If I edit the HTML in place using Dev Tools and change this to **.app**, the site works again.

The corresponding code in the Hugo template looks like this:

```
<link rel="stylesheet" href="{{ $css.RelPermalink }}">
```

Where `$css` is a relative path to `css/style.css`. 

I suspect that this is a DNS issue on Netlify's part that's happening because they've changed preview subdomains. DNS pointer issues usually take a maximum of 72 hours to sort themselves out, in my experience. 

As such, I'd recommend the following:
1) Trigger a rebuild of any affected previews via Netlify if you haven't. I don't have access to your Netlify console, unfortunately, so I can't help you here.
2) Wait it out for a day or two. 

If you're still seeing problems by Friday, then let's escalate.

**Comment by celestehorgan** [comment]
Update – per [netlifystatus.com](https://www.netlifystatus.com/), the migration is quite literally underway as we speak (last update was 10:52 PDT). Let's give their Ops team time and empathy to execute what will likely be the one of the most stressful migrations of their lives ;)

**Comment by morgo** [comment]
This is fixed. Thanks again for your help.
