### ISSUE TITLE
Add shortcut line item to Docs drop down menu for User Guides 

### ISSUE THREAD

**Issue by askdba** [vitessio/website#624]
On the main Vitess website to get to User Guides one has to either click on main Docs or drill down from other sub-menus. I think this is not practical as User Guides should have a shortcut.

**Comment by doeg** [comment]
I'd be happy to address this since it relates to https://github.com/vitessio/website/issues/618!

So currently, the "Docs" dropdown in the navbar [shows "featured" docs](https://github.com/vitessio/website/blob/prod/layouts/partials/navbar.html#L39): 

<img width="2672" alt="Screen Shot 2020-12-04 at 8 28 27 AM" src="https://user-images.githubusercontent.com/855595/101169351-c81f4f00-360a-11eb-90a5-e1c71b8bc6ec.png">

For #618, I've been thinking there are two approaches we could take (and would love input from everyone!):

1. Make the "Docs" link in the navbar a simple link, rather than a dropdown. Since we already have the sidebar nav on /docs, omitting a dropdown from the navbar is totally fine, I think, and even simplifies things nicely. This is what we do on all pages except /docs (and making this consistent is the goal of #618):

    <img width="2672" alt="Screen Shot 2020-12-04 at 8 40 08 AM" src="https://user-images.githubusercontent.com/855595/101170388-61029a00-360c-11eb-86ad-700e29b46611.png">

    And it's _also_ what https://kubernetes.io does, as one example:

    <img width="2672" alt="Screen Shot 2020-12-04 at 8 31 39 AM" src="https://user-images.githubusercontent.com/855595/101169614-349a4e00-360b-11eb-821c-8f2c59d163ac.png">

2. Keep the "Docs" link as a dropdown, but show first-level sections (and maybe second-level? but then what about third-level?) rather than "featured" articles. So, the "Docs" dropdown would look more like this (if we stick to first-order sections): 

    <img width="2672" alt="Screen Shot 2020-12-04 at 8 37 15 AM" src="https://user-images.githubusercontent.com/855595/101170121-f9e4e580-360b-11eb-9dc6-6da46d766c38.png">



@askdba it sounds like the second one might fit with what you're looking for... but did you have something else in mind? :) Another approach could be to add a "User Guides" link right in the navbar, adjacent to "Docs", "Blog", etc.

**Comment by askdba** [comment]
No, this looks fine. I just wanted to avoid users trying to figure out where docs are hidden. We can proceed with suggestions.

**Comment by askdba** [comment]
LGTM
