### ISSUE TITLE
both Google + site search are broken for user guides

### ISSUE THREAD

**Issue by derekperkins** [vitessio/website#921]
I'm guessing that these got broken on the last deployment.

- [ ] https://vitess.io/docs/user-guides/configuration-basic/monitoring/
- [ ] https://vitess.io/docs/user-guides/configuration-advanced/query-consolidation/

**Comment by mattlord** [comment]
Yeah, we should add redirects so that any `https://vitess.io/docs/...` link gets redirected to `https://vitess.io/docs/<latest>/...` which today would be this for the noted examples:
-  https://vitess.io/docs/12.0/user-guides/configuration-basic/monitoring/
-  https://vitess.io/docs/12.0/user-guides/configuration-advanced/query-consolidation/

**Comment by nate-double-u** [comment]
> Yeah, we should add redirects so that any `https://vitess.io/docs/...` link gets redirected to `https://vitess.io/docs/<latest>/...` which today would be this for the noted examples:
> 
>     * https://vitess.io/docs/12.0/user-guides/configuration-basic/monitoring/
> 
>     * https://vitess.io/docs/12.0/user-guides/configuration-advanced/query-consolidation/


The two variable redirects are `current` and `next`: 
https://github.com/vitessio/website/blob/246ed14f3436141c2bfb46f288be47edeca43123/layouts/index.redirects#L1-L2

so `https://vitess.io/docs/<latest>/...` should be `https://vitess.io/docs/<current>/...`


I think I see the problem:
https://github.com/vitessio/website/blob/246ed14f3436141c2bfb46f288be47edeca43123/layouts/index.redirects#L84-L85

looks like a copy paste error. If we fix the `:splat` forward this should work.
